import {ICountry} from '../../models/internal/country';

export const countries: ICountry[] = [
    { ab: "AF", name: "Afghanistan"},
    { ab: "AL", name: "Albania"},
    { ab: "DZ", name: "Algeria"},
    { ab: "AS", name: "American Samoa"},
    { ab: "AD", name: "Andorra"},
    { ab: "AO", name: "Angola"},
    { ab: "AI", name: "Anguilla"},
    { ab: "AQ", name: "Antarctica"},
    { ab: "AG", name: "Antigua and Barbuda"},
    { ab: "AR", name: "Argentina"},
    { ab: "AM", name: "Armenia"},
    { ab: "AW", name: "Aruba"},
    { ab: "AU", name: "Australia"},
    { ab: "AT", name: "Austria"},
    { ab: "AZ", name: "Azerbaijan"},
    { ab: "BS", name: "Bahamas (the)"},
    { ab: "BH", name: "Bahrain"},
    { ab: "BD", name: "Bangladesh"},
    { ab: "BB", name: "Barbados"},
    { ab: "BY", name: "Belarus"},
    { ab: "BE", name: "Belgium"},
    { ab: "BZ", name: "Belize"},
    { ab: "BJ", name: "Benin"},
    { ab: "BM", name: "Bermuda"},
    { ab: "BT", name: "Bhutan"},
    { ab: "BO", name: "Bolivia (Plurinational State of)"},
    { ab: "BQ", name: "Bonaire, Sint Eustatius and Saba"},
    { ab: "BA", name: "Bosnia and Herzegovina"},
    { ab: "BW", name: "Botswana"},
    { ab: "BV", name: "Bouvet Island"},
    { ab: "BR", name: "Brazil"},
    { ab: "IO", name: "British Indian Ocean Territory (the)"},
    { ab: "BN", name: "Brunei Darussalam"},
    { ab: "BG", name: "Bulgaria"},
    { ab: "BF", name: "Burkina Faso"},
    { ab: "BI", name: "Burundi"},
    { ab: "CV", name: "Cabo Verde"},
    { ab: "KH", name: "Cambodia"},
    { ab: "CM", name: "Cameroon"},
    { ab: "CA", name: "Canada"},
    { ab: "KY", name: "Cayman Islands (the)"},
    { ab: "CF", name: "Central African Republic (the)"},
    { ab: "TD", name: "Chad"},
    { ab: "CL", name: "Chile"},
    { ab: "CN", name: "China"},
    { ab: "CX", name: "Christmas Island"},
    { ab: "CC", name: "Cocos (Keeling) Islands (the)"},
    { ab: "CO", name: "Colombia"},
    { ab: "KM", name: "Comoros (the)"},
    { ab: "CD", name: "Congo (the Democratic Republic of the)"},
    { ab: "CG", name: "Congo (the)"},
    { ab: "CK", name: "Cook Islands (the)"},
    { ab: "CR", name: "Costa Rica"},
    { ab: "HR", name: "Croatia"},
    { ab: "CU", name: "Cuba"},
    { ab: "CW", name: "Curaçao"},
    { ab: "CY", name: "Cyprus"},
    { ab: "CZ", name: "Czechia"},
    { ab: "CI", name: "Côte d'Ivoire"},
    { ab: "DK", name: "Denmark"},
    { ab: "DJ", name: "Djibouti"},
    { ab: "DM", name: "Dominica"},
    { ab: "DO", name: "Dominican Republic (the)"},
    { ab: "EC", name: "Ecuador"},
    { ab: "EG", name: "Egypt"},
    { ab: "SV", name: "El Salvador"},
    { ab: "GQ", name: "Equatorial Guinea"},
    { ab: "ER", name: "Eritrea"},
    { ab: "EE", name: "Estonia"},
    { ab: "SZ", name: "Eswatini"},
    { ab: "ET", name: "Ethiopia"},
    { ab: "FK", name: "Falkland Islands (the) [Malvinas]"},
    { ab: "FO", name: "Faroe Islands (the)"},
    { ab: "FJ", name: "Fiji"},
    { ab: "FI", name: "Finland"},
    { ab: "FR", name: "France"},
    { ab: "GF", name: "French Guiana"},
    { ab: "PF", name: "French Polynesia"},
    { ab: "TF", name: "French Southern Territories (the)"},
    { ab: "GA", name: "Gabon"},
    { ab: "GM", name: "Gambia (the)"},
    { ab: "GE", name: "Georgia"},
    { ab: "DE", name: "Germany"},
    { ab: "GH", name: "Ghana"},
    { ab: "GI", name: "Gibraltar"},
    { ab: "GR", name: "Greece"},
    { ab: "GL", name: "Greenland"},
    { ab: "GD", name: "Grenada"},
    { ab: "GP", name: "Guadeloupe"},
    { ab: "GU", name: "Guam"},
    { ab: "GT", name: "Guatemala"},
    { ab: "GG", name: "Guernsey"},
    { ab: "GN", name: "Guinea"},
    { ab: "GW", name: "Guinea-Bissau"},
    { ab: "GY", name: "Guyana"},
    { ab: "HT", name: "Haiti"},
    { ab: "HM", name: "Heard Island and McDonald Islands"},
    { ab: "VA", name: "Holy See (the)"},
    { ab: "HN", name: "Honduras"},
    { ab: "HK", name: "Hong Kong"},
    { ab: "HU", name: "Hungary"},
    { ab: "IS", name: "Iceland"},
    { ab: "IN", name: "India"},
    { ab: "ID", name: "Indonesia"},
    { ab: "IR", name: "Iran (Islamic Republic of)"},
    { ab: "IQ", name: "Iraq"},
    { ab: "IE", name: "Ireland"},
    { ab: "IM", name: "Isle of Man"},
    { ab: "IL", name: "Israel"},
    { ab: "IT", name: "Italy"},
    { ab: "JM", name: "Jamaica"},
    { ab: "JP", name: "Japan"},
    { ab: "JE", name: "Jersey"},
    { ab: "JO", name: "Jordan"},
    { ab: "KZ", name: "Kazakhstan"},
    { ab: "KE", name: "Kenya"},
    { ab: "KI", name: "Kiribati"},
    { ab: "KP", name: "Korea (the Democratic People's Republic of)"},
    { ab: "KR", name: "Korea (the Republic of)"},
    { ab: "KW", name: "Kuwait"},
    { ab: "KG", name: "Kyrgyzstan"},
    { ab: "LA", name: "Lao People's Democratic Republic (the)"},
    { ab: "LV", name: "Latvia"},
    { ab: "LB", name: "Lebanon"},
    { ab: "LS", name: "Lesotho"},
    { ab: "LR", name: "Liberia"},
    { ab: "LY", name: "Libya"},
    { ab: "LI", name: "Liechtenstein"},
    { ab: "LT", name: "Lithuania"},
    { ab: "LU", name: "Luxembourg"},
    { ab: "MO", name: "Macao"},
    { ab: "MG", name: "Madagascar"},
    { ab: "MW", name: "Malawi"},
    { ab: "MY", name: "Malaysia"},
    { ab: "MV", name: "Maldives"},
    { ab: "ML", name: "Mali"},
    { ab: "MT", name: "Malta"},
    { ab: "MH", name: "Marshall Islands (the)"},
    { ab: "MQ", name: "Martinique"},
    { ab: "MR", name: "Mauritania"},
    { ab: "MU", name: "Mauritius"},
    { ab: "YT", name: "Mayotte"},
    { ab: "MX", name: "Mexico"},
    { ab: "FM", name: "Micronesia (Federated States of)"},
    { ab: "MD", name: "Moldova (the Republic of)"},
    { ab: "MC", name: "Monaco"},
    { ab: "MN", name: "Mongolia"},
    { ab: "ME", name: "Montenegro"},
    { ab: "MS", name: "Montserrat"},
    { ab: "MA", name: "Morocco"},
    { ab: "MZ", name: "Mozambique"},
    { ab: "MM", name: "Myanmar"},
    { ab: "NA", name: "Namibia"},
    { ab: "NR", name: "Nauru"},
    { ab: "NP", name: "Nepal"},
    { ab: "NL", name: "Netherlands (the)"},
    { ab: "NC", name: "New Caledonia"},
    { ab: "NZ", name: "New Zealand"},
    { ab: "NI", name: "Nicaragua"},
    { ab: "NE", name: "Niger (the)"},
    { ab: "NG", name: "Nigeria"},
    { ab: "NU", name: "Niue"},
    { ab: "NF", name: "Norfolk Island"},
    { ab: "MP", name: "Northern Mariana Islands (the)"},
    { ab: "NO", name: "Norway"},
    { ab: "OM", name: "Oman"},
    { ab: "PK", name: "Pakistan"},
    { ab: "PW", name: "Palau"},
    { ab: "PS", name: "Palestine, State of"},
    { ab: "PA", name: "Panama"},
    { ab: "PG", name: "Papua New Guinea"},
    { ab: "PY", name: "Paraguay"},
    { ab: "PE", name: "Peru"},
    { ab: "PH", name: "Philippines (the)"},
    { ab: "PN", name: "Pitcairn"},
    { ab: "PL", name: "Poland"},
    { ab: "PT", name: "Portugal"},
    { ab: "PR", name: "Puerto Rico"},
    { ab: "QA", name: "Qatar"},
    { ab: "MK", name: "Republic of North Macedonia"},
    { ab: "RO", name: "Romania"},
    { ab: "RU", name: "Russian Federation (the)"},
    { ab: "RW", name: "Rwanda"},
    { ab: "RE", name: "Réunion"},
    { ab: "BL", name: "Saint Barthélemy"},
    { ab: "SH", name: "Saint Helena, Ascension and Tristan da Cunha"},
    { ab: "KN", name: "Saint Kitts and Nevis"},
    { ab: "LC", name: "Saint Lucia"},
    { ab: "MF", name: "Saint Martin (French part)"},
    { ab: "PM", name: "Saint Pierre and Miquelon"},
    { ab: "VC", name: "Saint Vincent and the Grenadines"},
    { ab: "WS", name: "Samoa"},
    { ab: "SM", name: "San Marino"},
    { ab: "ST", name: "Sao Tome and Principe"},
    { ab: "SA", name: "Saudi Arabia"},
    { ab: "SN", name: "Senegal"},
    { ab: "RS", name: "Serbia"},
    { ab: "SC", name: "Seychelles"},
    { ab: "SL", name: "Sierra Leone"},
    { ab: "SG", name: "Singapore"},
    { ab: "SX", name: "Sint Maarten (Dutch part)"},
    { ab: "SK", name: "Slovakia"},
    { ab: "SI", name: "Slovenia"},
    { ab: "SB", name: "Solomon Islands"},
    { ab: "SO", name: "Somalia"},
    { ab: "ZA", name: "South Africa"},
    { ab: "GS", name: "South Georgia and the South Sandwich Islands"},
    { ab: "SS", name: "South Sudan"},
    { ab: "ES", name: "Spain"},
    { ab: "LK", name: "Sri Lanka"},
    { ab: "SD", name: "Sudan (the)"},
    { ab: "SR", name: "Suriname"},
    { ab: "SJ", name: "Svalbard and Jan Mayen"},
    { ab: "SE", name: "Sweden"},
    { ab: "CH", name: "Switzerland"},
    { ab: "SY", name: "Syrian Arab Republic"},
    { ab: "TW", name: "Taiwan"},
    { ab: "TJ", name: "Tajikistan"},
    { ab: "TZ", name: "Tanzania, United Republic of"},
    { ab: "TH", name: "Thailand"},
    { ab: "TL", name: "Timor-Leste"},
    { ab: "TG", name: "Togo"},
    { ab: "TK", name: "Tokelau"},
    { ab: "TO", name: "Tonga"},
    { ab: "TT", name: "Trinidad and Tobago"},
    { ab: "TN", name: "Tunisia"},
    { ab: "TR", name: "Turkey"},
    { ab: "TM", name: "Turkmenistan"},
    { ab: "TC", name: "Turks and Caicos Islands (the)"},
    { ab: "TV", name: "Tuvalu"},
    { ab: "UG", name: "Uganda"},
    { ab: "UA", name: "Ukraine"},
    { ab: "AE", name: "United Arab Emirates (the)"},
    { ab: "GB", name: "United Kingdom of Great Britain and Northern Ireland (the)"},
    { ab: "UM", name: "United States Minor Outlying Islands (the)"},
    { ab: "US", name: "United States of America (the)"},
    { ab: "UY", name: "Uruguay"},
    { ab: "UZ", name: "Uzbekistan"},
    { ab: "VU", name: "Vanuatu"},
    { ab: "VE", name: "Venezuela (Bolivarian Republic of)"},
    { ab: "VN", name: "Viet Nam"},
    { ab: "VG", name: "Virgin Islands (British)"},
    { ab: "VI", name: "Virgin Islands (U.S.)"},
    { ab: "WF", name: "Wallis and Futuna"},
    { ab: "EH", name: "Western Sahara"},
    { ab: "YE", name: "Yemen"},
    { ab: "ZM", name: "Zambia"},
    { ab: "ZW", name: "Zimbabwe"},
    { ab: "AX", name: "Åland Islands"}
];
